<!DOCTYPE html>
<!--[if lt IE 9 ]><html class="no-js oldie" lang="en"> <![endif]-->
<!--[if IE 9 ]><html class="no-js oldie ie9" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!-->
<html class="no-js" lang="pt">
<!--<![endif]-->

<head>
    <!--- basic page needs
   ================================================== -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="author" content="Patrick Tapajós - Prefeitura de Manaus">
    <meta http-equiv="pragma" content="no-cache" />
    <meta name="copyright" content="© 2017 Prefeitura de Manaus" />
    <meta name="description" content="O TRSD é um sistema utilizado pela Prefeitura de Manaus para realizar a declaração da quantidade lixo gerada por uma residência">
     
    <!-- mobile specific metas
   ================================================== -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSS
   ================================================== -->
    <link rel="stylesheet" href="portal/css/base.css">
    <link rel="stylesheet" href="portal/css/vendor.css">
    <link rel="stylesheet" href="portal/css/main.css">

    <!-- script
   ================================================== -->
    <script src="portal/js/modernizr.js"></script>
    <script src="portal/js/pace.min.js"></script>

    <!-- favicons
	================================================== -->
    <link rel="shortcut icon" href="portal/favicon.ico" type="image/x-icon">
    <link rel="icon" href="portal/favicon.ico" type="image/x-icon">

    <title>TRSD - Declaração de Taxa de Resíduos Sólidos Domésticos</title>
    
</head>

<body id="top">

  
   <header id="header" class="row">   
   		<div class="header-logo">
            <img src="portal/images/logo_2017_2020.png" width="200" data-aos="fade-up">
        </div> 
        <nav id="header-nav-wrap">
            <ul class="header-main-nav">
                <li class="current"><a class="smoothscroll"  href="#declaracao" title="Como funciona a declaração">Como funciona a declaração</a></li>
                <li class="current"><a href="<?= $url ?>" title="Efetuar a Declaração" class="stroke" target="_blank">Efetuar a Declaração</a></li>
            </ul>
        </nav>
        <a class="header-menu-toggle" href="#"><span>Menu</span></a>    	
   </header>  

   <!-- home
   ================================================== -->
   <section id="home" data-parallax="scroll" data-image-src="portal/images/topo.png">

        <div class="overlay"></div>
        <div class="home-content">        
            <div class="row contents">                     
                <div class="home-content-left">
                    
                    <h3 data-aos="fade-up">Olá, contribuinte</h3>

                    <h1 data-aos="fade-up">
                        Você sabia que <br>
                        pode contribuir ainda mais para <br>
                        uma cidade melhor?
                    </h1>

                    <div class="buttons aos-init aos-animate" data-aos="fade-up">
                        <a href="<?= $url ?>" target="_blank" class="button stroke">
                            <span class="icon-play" aria-hidden="true"></span>
                            Efetuar a Declaração
                        </a>
                    </div>

                    <!-- <h1 data-aos="fade-up">
                        Você contribui <br>
                        para uma cidade <br>
                        cada vez melhor
                    </h1> -->

                </div>
            </div>

        </div> <!-- end home-content -->

   

    </section> <!-- end home -->  


    <!-- about
    ================================================== -->
    <section id="about">

        <div class="row about-intro">

            <div class="col-four">
                <h1 class="intro-header" data-aos="fade-up">Declaração de Resíduos Sólidos Domésticos</h1>
            </div>
            <div class="col-eight">
                <p class="lead" data-aos="fade-up">
                    Em cumprimento à Lei Complementar nº 001 de 20 de janeiro de 2010, que dispõe sobre a organização do Sistema de Limpeza Urbana do município de Manaus e institui a Taxa de Resíduos Sólidos Domiciliares (TRSD), a Prefeitura de Manaus passa a implementar, neste próximo exercício, a cobrança da ‘Taxa do Lixo’ aos contribuintes da capital cujo IPTU ultrapasse a 7,2 UFMs para o lançamento de 2019. Abaixo do estipulado, o contribuinte ficará isento da taxa.
                </p>
            </div>     
            
        </div>
        

        <div class="row about-features">

            <div class="features-list block-1-2 block-m-1-2 block-mob-full group">

                <div class="bgrid feature aos-init aos-animate" data-aos="fade-up">	

                    <h1>Você sabia?</h1>

                    <div class="service-content">	

                        <img src="portal/images/toneladas.png" width="200" data-aos="fade-up">
                        <p class="lead">
                        Foi o total de resíduos sólidos recolhidos na nossa cidade em 2017, o que dá uma média diária de 2.432 toneladas, com uma coleta percapta de 1,142 quilos por dia.
                        </p>

                        <img src="portal/images/milhoes.png" width="200" data-aos="fade-up">
                        <p class="lead">
                        Foi o valor gasto no ano passado pela Prefeitura de Manaus para realização das ações de limpeza pública, o que incluiu coleta de resíduos, mutirões e limpeza de igarapés.
                        </p>
                        
                    </div> 	         	 

                </div> <!-- /bgrid -->

                 <div class="bgrid feature aos-init aos-animate" data-aos="fade-up">	

                    <div class="service-content">	

                        <div class="image-right"><img src="portal/images/boneco.png" data-aos="fade-up" width="60%"></div>
                        
                    </div> 	         	 

                </div> <!-- /bgrid -->

            </div> <!-- end features-list -->

        </div>
    

        <div class="row about-how" id="declaracao">
          
            <h1 class="intro-header" data-aos="fade-up">Como funciona a declaração?</h1>           

            <div class="about-how-content" data-aos="fade-up">
                <div class="about-how-steps block-1-2 block-tab-full group">

                    <div class="bgrid step" data-item="1">
                        <h3>Identificação do Contribuinte</h3>
                        <p>Insira a matrícula de IPTU do imóvel onde você reside e seu CPF (ou o CPF do proprietário do imóvel). 
                        </p> 
                    </div>

                    <div class="bgrid step" data-item="2">
                        <h3>Verificação dos dados</h3>
                        <p>Verifique se os dados do imóvel estão corretos. Caso haja algum erro, siga as instruções na tela de verificação. 
                        </p> 
                    </div>               
               
                    <div class="bgrid step" data-item="3">
                        <h3>Formulário de Declaração</h3>
                        <p>Informe a quantidade pessoas que moram com você e a quantidade de resíduos sólidos (o famigerado lixo) produzida. 
                        </p> 
                    </div>

                    <div class="bgrid step" data-item="4">
                        <h3>Download de comprovante</h3>
                        <p>Faça o download do comprovante para certificar que seu cadastro foi realizado com sucesso.
                        </p> 
                    </div>  

                </div>          

           </div> <!-- end about-how-content -->

            <div class="buttons text-center">
                <a href="<?= $url ?>" target="_blank">
                    <button class="button button-primary" type="button">Efetuar a declaração</button>
                </a>
            </div>

        </div> <!-- end about-how -->
                                    
    </section> <!-- end about -->  
   
    <!-- footer
    ================================================== -->
    <footer>

      <div class="footer-bottom">
        <img src="portal/images/brasao.png" width="64">
      	<div class="row">
      		<div class="col-twelve">
	      		<div class="copyright">
		         	<span>© Copyright SUBTI - Prefeitura de Manaus 2017.</span> 
		         	<span>Baseado em <a href="http://www.styleshout.com/">styleshout</a></span>		         	
		         </div>

		         <div id="go-top">
		            <a class="smoothscroll" title="Voltar para o topo" href="#top"><i class="icon-arrow-up"></i></a>
		         </div>         
	      	</div>

      	</div> <!-- end footer-bottom -->     	

      </div>

    </footer>

    <div id="preloader"> 
    	<div id="loader"></div>
    </div>  

    <!-- Java Script
    ================================================== -->
    <script src="portal/js/jquery-2.1.3.min.js"></script>
    <script src="portal/js/plugins.js"></script>
    <script src="portal/js/main.js"></script>

</body>

</html>